name: Generate Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'docs/**'
      - 'generate_doc.sh'

jobs:
  build-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run generation script
        run: |
          chmod +x generate_doc.sh
          ./generate_doc.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto-generate html documentation from markdown"
          file_pattern: 'doc/*.html doc/*.css'
          branch: main