name: EcoDrop CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. On installe Pandoc et on génère la doc à la volée
      - name: Build HTML Documentation
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          chmod +x generate_doc.sh
          ./generate_doc.sh

      # 2. On envoie TOUT (le code source ET le nouveau dossier /doc généré) sur le serveur
      - name: Secure Copy Code to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/jpro-deployment/ecodrop-api"

      # 3. On demande à Docker de recompiler l'application
      - name: Rebuild Infrastructure
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/jpro-deployment
            sudo docker compose up -d --build ecodrop-app