name: EcoDrop CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run generation script
        run: |
          chmod +x generate_doc.sh
          ./generate_doc.sh

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: auto-generate html documentation from markdown"
          file_pattern: 'doc/*.html doc/*.css'
          branch: main

  deploy:
    needs: build-doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Secure Copy Code to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/jpro-deployment/ecodrop-api"

      - name: Rebuild Infrastructure
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/jpro-deployment
            sudo docker compose up -d --build ecodrop-app
